// src/routes/ftm/[station]/+page.svelte
<script lang="ts">
	import { PUBLIC_BASE_URL } from '$env/static/public';
	import Train from './FtmTrain.svelte';
	import FooterNavigation from '$lib/components/FooterNavigation.svelte';
	import { onMount, setContext } from 'svelte';
	import { invalidateAll } from '$app/navigation';
	import { flip } from 'svelte/animate';
	import { fade } from 'svelte/transition';
	import ModesSwitch from '$lib/components/ModesSwitch.svelte';
	import StationFavoriteButton from '$lib/components/StationFavoriteButton.svelte';
	import type { ExpandedTripState } from '$lib/Trip';
	import LiveTripAnimation from '../../[stop]/LiveTripAnimation.svelte';
	import { Flag } from 'lucide-svelte';

	let { data } = $props();

	let details = $derived(data.details);
	let showMore = $state(false);
	let showMoreInProgress = $state(false);
	let limit = $derived(showMore ? Infinity : 5);

	const REFRESH_INTERVAL = 30 * 1000;
	let timer: ReturnType<typeof setInterval>;

	function onVisibilityChange() {
		clearInterval(timer);
		if (document.visibilityState != 'hidden') {
			invalidateAll();
			timer = setInterval(invalidateAll, REFRESH_INTERVAL);
		}
	}

	const tripState: ExpandedTripState = {
		id: null
	};
	const expandedTrip = $state(tripState);
	setContext('expandedTrip', expandedTrip);

	onMount(() => {
		timer = setInterval(invalidateAll, REFRESH_INTERVAL);
		document.addEventListener('visibilitychange', onVisibilityChange);
		return () => {
			clearInterval(timer);
			document.removeEventListener('visibilitychange', onVisibilityChange);
		};
	});
</script>

<svelte:head>
	<title>Stazione di {details.name}</title>
	<link rel="canonical" href="{PUBLIC_BASE_URL}/treni/{details.canonicalSlug}" />
</svelte:head>

<header>
	<h1 class="text-center text-4xl font-semibold">
		Stazione di {details.name}
		<StationFavoriteButton stationId={details.id} className="pl-1" />
	</h1>
	<div class="mt-1 text-center text-sm">
		aggiornato alle
		{new Date(details.lastUpdatedAt).toLocaleTimeString(['it-IT'], {
			hour: '2-digit',
			minute: '2-digit'
		})}
	</div>

	{#if details.stopMapping}
		<div class="mt-6 flex justify-center">
			<ModesSwitch
				selectedTab={'ftm'}
				stopMapping={details.stopMapping}
			/>
		</div>
	{/if}
</header>

<main>
	<div class="mt-10 flex flex-col">
		{#if details.trains.length > 0}
			{#each details.trains.slice(0, limit) as train (train.id)}
				<div
					animate:flip={{ delay: 300 }}
					in:fade={{ delay: showMoreInProgress ? 0 : 800, duration: 300 }}
					out:fade={{ duration: 300 }}
				>
					<Train {train} userPosition={details.position}/>
				</div>
			{/each}

			{#if !showMore && details.trains.length > limit}
				<button
					class="text-mid mt-2 rounded-md bg-neutral-800 px-3 py-1 no-underline hover:bg-neutral-700"
					onclick={() => {
						showMore = true;
						showMoreInProgress = true;
						setTimeout(() => {
							showMoreInProgress = false;
						}, 50);
					}}
				>
					Mostra tutti
				</button>
			{/if}
		{:else}
			<div class="text-center">Nessun treno previsto</div>
		{/if}
	</div>
</main>

<footer class="my-12">
	<div class="space-y-2 text-sm text-neutral-500">
		<p>
			Dati in tempo reale Algorab. Gli orari si riferiscono agli orari programmati di arrivo dei treni.
			I dati sugli autobus sostitutivi non sono presenti, verifica sul sito di Trentino Trasporti.
		</p>

		<p class="mt-2">
			Il pallino verde
			<LiveTripAnimation className="inline-block mx-1" live="green" />
			indica che i dati sono in tempo reale.
		</p>

		<p>
			Il simbolo
			<Flag class="inline size-4" />
			indica che la corsa terminerà in questa stazione.
		</p>

		<p>La pagina si aggiorna automaticamente ogni 30 secondi.</p>
	</div>

	<FooterNavigation className="mt-6" isBus={false} />
</footer>

// pages/treni/[station].vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref, useHead, useLazyFetch, useRoute, watch } from '#imports';

enum ResponseError {
    NotFound = 1,
    NotMyFault = 2,
    Unknown = 3,
}

/* State */
let stationSlug: string;
const isLoading = ref(true);
let data = ref<StationsResponse | null>(null);
let error = ref<ResponseError | null>(null);
let refreshData: Function;
let timer: NodeJS.Timer;

/* Methods */
function readStationSlug() {
    const route = useRoute();
    stationSlug = route.params.station as string;
}

async function loadStation() {
    let response = useLazyFetch<StationsResponse>(() => `/api/stations/${stationSlug}`);

    refreshData = response.refresh;

    watch(response.error, () => {
        if (response.error.value) {
            isLoading.value = false;
            error.value = ResponseError.Unknown;

            if (response.error.value instanceof Error) {
                let err: any = response.error.value;
                if (err.response) {
                    if (err.response.status === 404) {
                        error.value = ResponseError.NotFound;
                    } else if (err.response.status === 503) {
                        error.value = ResponseError.NotMyFault;
                    }
                }
            }
        } else {
            isLoading.value = false;
            error.value = null;
        }
    });

    watch(response.data, () => {
        data.value = response.data.value;

        if (data.value) {
            useHead({
                title: 'Stazione di ' + data.value.stationName,
            });

            // Initial loading finished
            if (isLoading.value) {
                isLoading.value = false;
                // Start refresh timer
                timer = startRefreshTimer();
            }
        }
    });
}

async function requestRefresh() {
    console.log('Refreshing...');
    await refreshData();
}

function startRefreshTimer(milliseconds = 30 * 1000) {
    return setInterval(requestRefresh, milliseconds);
}

async function onVisibilityChange() {
    if (document.visibilityState == 'hidden') {
        clearInterval(timer);
    } else if (error.value != ResponseError.NotFound) {
        timer = startRefreshTimer();
        await requestRefresh();
    }
}

/* Lifecycle */
onMounted(() => {
    document.addEventListener('visibilitychange', onVisibilityChange);
});

onUnmounted(() => {
    clearInterval(timer);
    document.removeEventListener('visibilitychange', onVisibilityChange);
});

readStationSlug();
await loadStation();
</script>

<template>
    <div>
        <div v-if="isLoading" class="text-center">Caricamento...</div>
        <div v-else-if="error" class="text-center">
            <template v-if="error === ResponseError.NotFound">
                <p>Stazione ferroviaria non trovata</p>
            </template>
            <template v-else-if="error === ResponseError.NotMyFault">
                <p>I dati sui treni non sono al momento disponibili 😕</p>
                <p>Prova a ricaricare la pagina.</p>
            </template>
            <template v-else>
                <p>Si è verificato un errore 😕</p>
                <p>Prova a ricaricare la pagina.</p>
            </template>

            <div class="my-10 text-neutral-500 text-sm text-center">
                <NuxtLink to="/treni">Lista stazioni (treni)</NuxtLink>
                -
                <NuxtLink to="/">Lista fermate (autobus)</NuxtLink>
                -
                <NuxtLink to="/info">Informazioni</NuxtLink>
            </div>
        </div>
        <template v-else-if="data">
            <header>
                <h1 class="font-semibold text-center text-4xl">Stazione di {{ data.stationName }}</h1>
                <div class="mt-1 text-sm text-center">
                    aggiornato alle
                    {{
                        new Date(data.lastUpdatedAt).toLocaleTimeString([], {
                            hour: '2-digit',
                            minute: '2-digit',
                        })
                    }}
                </div>
            </header>

            <main>
                <Switch
                    v-if="data.busSlug != null"
                    class="mt-6"
                    :is-bus="false"
                    :bus-slug="data.busSlug"
                    :train-slug="stationSlug"
                />
                <div class="mt-10">
                    <Train v-for="train in data.trains" :train="train" />
                </div>
                <div v-if="data.trains.length === 0" class="text-center">Nessun treno previsto</div>
            </main>

            <footer class="my-12">
                <div class="text-sm text-neutral-500">
                    <div>
                        Dati RFI. I dati si riferiscono alle partenze. La granularità dei ritardi è di 5 minuti. I dati
                        sugli autobus sostitutivi non sono sempre affidabili, verifica sugli orari.
                    </div>

                    <div class="mt-2">
                        <span class="inline-block w-5">
                            <span class="animate-blink block rounded-full w-2 h-2 bg-white"></span>
                        </span>
                        indica che il treno è in partenza.
                    </div>

                    <div class="mt-2">
                        ⚠️ indica che i dettagli sul treno cancellato sono temporaneamente non disponibili (il treno
                        potrebbe essere sostituito da bus).
                    </div>

                    <div class="mt-2">La pagina si aggiorna automaticamente ogni 30 secondi.</div>
                </div>

                <div class="mt-6 flex flex-col items-start gap-y-3">
                    <NuxtLink class="px-3 py-1 rounded-md no-underline bg-neutral-800 hover:bg-neutral-700" to="/">
                        🚍 Lista fermate autobus
                    </NuxtLink>

                    <NuxtLink class="px-3 py-1 rounded-md no-underline bg-neutral-800 hover:bg-neutral-700" to="/treni">
                        🚆 Lista stazioni treni
                    </NuxtLink>

                    <NuxtLink class="px-3 py-1 rounded-md no-underline bg-neutral-800 hover:bg-neutral-700" to="/info">
                        ℹ️ Informazioni
                    </NuxtLink>
                </div>
            </footer>
        </template>
    </div>
</template>
