// src/routes/treni/+page.svelte
<script lang="ts">
	import { slide, fade } from 'svelte/transition';
	import { flip } from 'svelte/animate';
	import ModesSwitch from '$lib/components/ModesSwitch.svelte';
	import TabButton from '$lib/components/TabButton.svelte';
	import StationBlock from './StationBlock.svelte';
	import { onMount, setContext } from 'svelte';
	import { distance, getCurrentPosition, handleGeolocationError, isGeolocationGranted } from '$lib/location-helpers';
	import { createFavoritesStore } from '$lib/stores/stations-favorites';
	import { getDefaultTab, setDefaultTab, type Tab } from '$lib/storage/stations-default-tab';

	export let data;

	let activeTab = getDefaultTab();

	let searchTerm = '';
	let selectedRailway = '';

	let showGeolocationButton = false;
	let distances = new Map<string, number>();

	const favorites = createFavoritesStore();
	setContext('favorites', favorites);

	$: sortedStations = data.stations
		// Sort by distance
		.sort((a, b) => (distances.get(a.id) ?? Infinity) - (distances.get(b.id) ?? Infinity));

	$: filteredStations = data.stations
		.filter((station) =>
			// Filter by railway. Evaluates to true if no route is selected
			(selectedRailway == '' || station.railways.includes(selectedRailway)) &&
			// Filter by search term on the name. Evaluates to true if no search term is present
			(searchTerm == '' ||
				station.name.toLowerCase().includes(searchTerm.toLowerCase())
			)
		);

	$: favoriteStations = data.stations.filter(x => $favorites.has(x.id));

	onMount(async () => {
		if (await isGeolocationGranted()) {
			await updatePosition();
		} else {
			showGeolocationButton = true;
		}
	});

	async function updatePosition() {
		try {
			const position = await getCurrentPosition();

			// Recalculate distances
			for (let station of data.stations) {
				distances.set(station.id, distance(position.coords, station.coordinates));
			}

			distances = distances; // trigger re-render
			showGeolocationButton = false;
		} catch (err) {
			handleGeolocationError(err);
		}
	}

	function switchTab(tab: Tab) {
		activeTab = tab;
		searchTerm = '';
		selectedRailway = '';
		setDefaultTab(tab);
	}

	export const snapshot = {
		capture: () => ({
			searchTerm, selectedRailway
		}),
		restore: (values) => {
			searchTerm = values.searchTerm;
			selectedRailway = values.selectedRailway;
		}
	};
</script>

<svelte:head>
	<title>Tra quanto passa</title>
</svelte:head>

<header class="text-center">
	<h1 class="font-semibold text-4xl">Tra quanto passa in...</h1>
	<div class="mt-2 text-neutral-500 text-lg">Ferrovia del Brennero e della Valsugana</div>
</header>

<main>
	<div class="mt-8 flex justify-center">
		<ModesSwitch isBus={false} />
	</div>

	<div class="mt-8 flex max-sm:flex-wrap gap-2 xs:gap-3" style="scrollbar-width: none">
		<TabButton text="📍 Più vicine" isSelected={activeTab === 'all'} onClick={() => switchTab('all')} />
		<TabButton text="🔍 Cerca" isSelected={activeTab === 'filter'} onClick={() => switchTab('filter')} />
		<TabButton text="⭐️ Preferiti" isSelected={activeTab === 'favorites'} onClick={() => switchTab('favorites')} />
	</div>

	{#if activeTab === 'all' || activeTab === 'filter'}
		<div class="{activeTab === 'all' && showGeolocationButton ? 'mt-4' : 'mt-8'}">
			{#if activeTab === 'all' && showGeolocationButton}
				<button on:click={updatePosition}
								in:slide
								class="px-3.5 py-2 w-full text-center">
					⚠️ Consenti accesso alla posizione
				</button>
			{/if}

			{#if activeTab === 'filter'}
				<div class="mt-4 flex max-sm:flex-col gap-x-4 gap-y-3">
					<input
						type="search"
						placeholder="🔍 Cerca stazione..."
						class="w-full basis-1/2 px-3.5 py-2 rounded-md bg-neutral-800 text-neutral-100 focus:outline focus:outline-2 focus:outline-neutral-700"
						bind:value={searchTerm}
					/>

					<select
						bind:value={selectedRailway}
						class="w-full basis-1/2 py-2 px-3.5 rounded-md bg-neutral-800 text-neutral-100 focus:outline focus:outline-2 focus:outline-neutral-700">
						<option value="">🚂 Filtra per ferrovia</option>
						{#each data.railways as railway (railway)}
							<option value={railway}>{railway}</option>
						{/each}
					</select>
				</div>

				{#if searchTerm || selectedRailway}
					<button class="w-full mt-4 px-3.5 py-2 rounded-md bg-neutral-800 hover:bg-neutral-700"
									on:click={() => { searchTerm = ''; selectedRailway = ''; }}>
						❌ Rimuovi filtri
					</button>
				{/if}
			{/if}

			<div class="mt-4 text-lg grid xs:grid-cols-2 gap-4">
				{#each (activeTab === 'all' ? sortedStations : filteredStations) as station (station.id)}
					<StationBlock {station} isFavorite={$favorites.has(station.id)} />
				{/each}
			</div>
		</div>
	{:else}
		<div class="mt-8">
			{#if favoriteStations.length === 0}
				<p class="mb-2 text-neutral-500 text-center">
					Premi l'icona della stella su una stazione per aggiungerla ai preferiti.
				</p>
			{/if}

			<div class="text-lg grid xs:grid-cols-2 gap-4">
				{#each favoriteStations as station (station.id)}
					<div class="flex shrink-0"
							 animate:flip={{duration: 500, delay: 1000}}
							 out:fade={{delay: 1000, duration: 100}}>
						<StationBlock {station} isFavorite={true} />
					</div>
				{/each}
			</div>
		</div>
	{/if}
</main>

<footer class="mb-12 mt-14 text-center">
	<a class="px-3 py-2 rounded-md no-underline bg-neutral-800 hover:bg-neutral-700" href="/info">
		ℹ️ Informazioni
	</a>
</footer>

// pages/treni/index.vue
<script setup lang="ts">
// TODO: this is a huge copy paste from the other index, refactor

import { computed, ref, useFetch, useHead } from '#imports';

/* State */
const stations = ref<StationWithDistance[]>([]);
const showSortButton = ref(false);
const searchTerm = ref('');
const filteredStations = computed(() => {
    // Sort stops by distance (copy to avoid mutating the original array)
    const sortedStations = [...stations.value].sort((a, b) => a.distance - b.distance);

    return sortedStations.filter(
        (station) =>
            // Filter by search term on both name and slug. Evaluates to true if no search term is present
            searchTerm.value == '' ||
            station.name.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
            station.slug.toLowerCase().includes(searchTerm.value.toLowerCase())
    );
});

/* Methods */
async function loadStations() {
    const res = await useFetch<StationWithDistance[]>('/api/stations');
    if (res.data.value) {
        stations.value = res.data.value;
    }
}

async function checkGeo() {
    // Safari doesn't support permissions API, so we can't check if the permission was granted
    if (!navigator.permissions) {
        showSortButton.value = true;
        return;
    }

    let permission = await navigator.permissions.query({ name: 'geolocation' });
    if (permission.state === 'granted') {
        sortByPosition();
    } else if (permission.state === 'prompt') {
        showSortButton.value = true;
    }
}

function sortByPosition() {
    navigator.geolocation.getCurrentPosition(
        (pos) => {
            showSortButton.value = false;
            let coords = pos.coords;
            for (let station of stations.value) {
                station.distance = Math.sqrt(
                    Math.pow(station.coordinates[0] - coords.latitude, 2) +
                        Math.pow(station.coordinates[1] - coords.longitude, 2)
                );
            }
        },
        (err) => {
            if (err.code == err.PERMISSION_DENIED) {
                alert(
                    'La richiesta di accesso alla posizione è stata negata. Verifica le autorizzazioni al sito nelle impostazioni del tuo browser.'
                );
            } else {
                alert("Si è verificato un errore durante l'ottenimento della posizione");
            }
        }
    );
}

function updateHead() {
    useHead({
        title: 'Tra quanto passa',
    });
}

/* On created */
updateHead();
await loadStations();
await checkGeo();
</script>

<template>
    <div>
        <header>
            <h1 class="font-semibold text-4xl">Tra quanto passa in...</h1>
            <div class="mt-2 text-neutral-500 text-lg">Ferrovia del Brennero e della Valsugana</div>
        </header>

        <main>
            <div class="mt-8 flex justify-between xs:flex-row flex-col gap-2 text-mid">
                <Switch :is-bus="false" bus-slug="" train-slug="" align="left" />

                <button
                    v-if="showSortButton"
                    @click="sortByPosition"
                    class="h-8 flex items-center justify-center xs:basis-[190px] bg-neutral-800 hover:bg-neutral-700 px-3 rounded-md text-ellipsis whitespace-nowrap overflow-hidden"
                >
                    📍 Ordina per vicinanza
                </button>
            </div>

            <div class="mt-2 flex flex-row gap-2 text-mid">
                <input
                    type="search"
                    placeholder="🔍 Cerca stazione..."
                    class="w-full h-8 pl-3 rounded-md bg-neutral-800 text-neutral-100 focus:outline focus:outline-2 focus:outline-neutral-700"
                    v-model="searchTerm"
                />
            </div>

            <div class="mt-10 text-lg grid grid-cols-2 gap-4">
                <NuxtLink
                    v-for="station in filteredStations"
                    :to="`/treni/${station.slug}`"
                    class="flex flex-col no-underline bg-neutral-800 rounded-lg px-4 pt-2 pb-3"
                >
                    {{ station.name }}
                    <span class="grow text-sm no-underline text-neutral-500">/{{ station.slug }}</span>
                    <span class="mt-2 text-xs font-semibold text-neutral-500">{{ station.railway }}</span>
                </NuxtLink>
            </div>
        </main>

        <footer class="mb-12 mt-14 text-center">
            <NuxtLink class="px-3 py-2 rounded-md no-underline bg-neutral-800 hover:bg-neutral-700" to="/info">
                ℹ️ Informazioni
            </NuxtLink>
        </footer>
    </div>
</template>
