// components/Trip.vue
<script setup lang="ts">
defineProps<{ trip: Trip }>();

function formatMinutes(minutes: number) {
    if (minutes < 60) {
        return `${minutes}'`;
    } else {
        let hours = Math.floor(minutes / 60);
        let minutesLeft = minutes % 60;
        if (minutesLeft === 0) {
            return `${hours}h`;
        } else {
            return `${hours}h ${minutesLeft}m`;
        }
    }
}
</script>

<template>
    <div class="flex items-center gap-x-4 mb-2">
        <div
            class="w-10 h-10 flex-shrink-0 flex justify-center items-center font-bold text-xl rounded-md select-none"
            :style="{ backgroundColor: trip.routeColor }"
        >
            {{ trip.routeName }}
        </div>
        <div class="flex-grow whitespace-nowrap overflow-hidden">
            <span class="block leading-tight text-lg font-medium text-ellipsis overflow-hidden whitespace-nowrap">
                {{ trip.destination }}
            </span>
            <span class="block leading-none text-xs text-neutral-500">
                <template v-if="trip.distanceInStops != null">
                    <template v-if="trip.distanceInStops === -2"> oltre la tua fermata</template>
                    <template v-else-if="trip.distanceInStops === -1"> non ancora partito</template>
                    <template v-else-if="trip.distanceInStops === 0"> alla tua fermata</template>
                    <template v-else-if="trip.distanceInStops === 1">
                        a {{ trip.distanceInStops }} fermata da te
                    </template>
                    <template v-else> a {{ trip.distanceInStops }} fermate da te </template>
                    <template v-if="trip.delay != null"> • </template>
                </template>
                <template v-if="trip.delay != null">
                    <template v-if="trip.delay === 0">in orario</template>
                    <template v-else-if="trip.delay > 0">in ritardo di {{ trip.delay }} min</template>
                    <template v-else>in anticipo di {{ -trip.delay }} min</template>
                </template>
            </span>
        </div>
        <div
            class="text-right text-xl font-semibold whitespace-nowrap"
            :class="{ 'animate-pulse': trip.minutes === 0, 'text-red-600': trip.minutes === 0 }"
        >
            {{ formatMinutes(trip.minutes) }}
        </div>
        <span class="rounded-full w-2 h-2 animate-ping" :class="{ 'bg-green-500': trip.delay != null }"></span>
    </div>
</template>

// src/routes/[stop]/Trip.svelte
<script lang="ts">
	import type { Trip } from '$lib/Trip';
	import LiveTripAnimation from './LiveTripAnimation.svelte';
	import PulsingMinutes from './PulsingMinutes.svelte';
	import { Flag } from 'lucide-svelte';
	import BusTripDetail from './BusTripDetail.svelte';
	import { slide } from 'svelte/transition';
	import { getContext } from 'svelte';
	import type { Writable } from 'svelte/store';

	export let trip: Trip;

	const expandedTripId = getContext<Writable<string | null>>('expandedTripId');
	$: expanded = $expandedTripId === trip.id;
</script>

<div class="flex items-center gap-x-4 mb-2 cursor-pointer"
		 role="button" aria-expanded={expanded}
		 on:click={() => $expandedTripId = trip.id} tabindex="0"
		 on:keypress={(e) => (e.key === 'Enter' ? ($expandedTripId = trip.id) : null)}
>
	<div
		class="w-10 h-10 flex-shrink-0 flex justify-center items-center font-bold text-xl rounded-md select-none"
		style="background-color: {trip.routeColor}"
	>
		{trip.routeName}
	</div>
	<div class="flex-grow whitespace-nowrap overflow-hidden">
		<span
			class="flex gap-x-2 items-center leading-tight text-lg text-ellipsis overflow-hidden whitespace-nowrap"
			class:text-neutral-500={trip.isEndOfRouteForUser}
			class:font-medium={!trip.isEndOfRouteForUser}>
			{trip.destination}
			{#if trip.isEndOfRouteForUser}
				<Flag class="size-4" strokeWidth={2.5} />
			{/if}
		</span>
		<span class="block leading-none text-xs text-neutral-500">
			{#if trip.delay != null}
				{@const distanceInStops = trip.userStopSequenceNumber - trip.currentStopSequenceNumber}

				{#if trip.currentStopSequenceNumber === 0}
					non ancora partito
				{:else if distanceInStops < 0}
					oltre la tua fermata
				{:else if distanceInStops === 0}
					alla tua fermata
				{:else if distanceInStops === 1}
					a 1 fermata da te
				{:else}
					a {distanceInStops} fermate da te
				{/if}
				{#if trip.currentStopSequenceNumber <= 1}
					(capolinea)
				{/if}

				•

				{#if trip.delay === 0}
					in orario
				{:else if trip.delay > 0}
					in ritardo di {trip.delay} min
				{:else}
					in anticipo di {-trip.delay} min
				{/if}
			{/if}
		</span>
	</div>
	<PulsingMinutes minutes={trip.minutes} dimmed={trip.isEndOfRouteForUser} />
	<LiveTripAnimation live={trip.delay != null ? (trip.isOutdated ? 'yellow' : 'green') : null} />
</div>

{#if expanded}
	<div transition:slide={{ duration: 300}}>
		<BusTripDetail {trip} />
	</div>
{/if}
